package thesimpleems_16nov;

import com.formdev.flatlaf.*;
import thesimpleems_16nov.FTE;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author P0068839
 */
public class MainJFrame extends javax.swing.JFrame {
    
    // ATTRIBUTES
    public MyHashTable theHT;
    boolean light = false;
    
    
    // CONSTRUCTORS
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        if(light){
            jToggleButton1.setText("Light");
        }else{
            jToggleButton1.setText("Dark");
        }
        
        // Reading from database file
        try {
            BufferedReader br = new BufferedReader(new FileReader("database.json"));
            
            
            br.close();
        } catch (FileNotFoundException ex) {
            System.err.println("File Not Found!");
        } catch (IOException ex) {
            System.err.println("Invalid File!");
        }
        
        
        theHT = new MyHashTable(10);
        System.out.println("Created HashTable");
        
    }
    
    
    // METHODS   
    
    public MyHashTable getTheHT() {
        return theHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tempJButton1 = new javax.swing.JButton();
        tempJButton2 = new javax.swing.JButton();
        tempJButton3 = new javax.swing.JButton();
        addEmpButton = new javax.swing.JButton();
        removeEmpButton = new javax.swing.JButton();
        getEmpInfoButton = new javax.swing.JButton();
        setEmpInfoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tempJButton1.setText("Create three employees, add to hash table");
        tempJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempJButton1ActionPerformed(evt);
            }
        });

        tempJButton2.setText("Clear Database");
        tempJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempJButton2ActionPerformed(evt);
            }
        });

        tempJButton3.setText("Display All Employees");
        tempJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_tempJButton3(evt);
            }
        });

        addEmpButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        addEmpButton.setText("Add Employee");
        addEmpButton.setToolTipText("Add a new Employee to the system");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });

        removeEmpButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        removeEmpButton.setText("Remove Employee");
        removeEmpButton.setToolTipText("Remove an existing Employee");
        removeEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmpButtonActionPerformed(evt);
            }
        });

        getEmpInfoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getEmpInfoButton.setText("Lookup Employee Information");
        getEmpInfoButton.setToolTipText("Get Information based on Employee Number");
        getEmpInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmpInfoButtonActionPerformed(evt);
            }
        });

        setEmpInfoButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        setEmpInfoButton.setText("Change Employee Information");
        setEmpInfoButton.setToolTipText("Change Employee number, name, work location, etc.");
        setEmpInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEmpInfoButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("HR Employee Management System");

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Dark");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getEmpInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setEmpInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tempJButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tempJButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempJButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(removeEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setEmpInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getEmpInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(tempJButton1)
                .addGap(18, 18, 18)
                .addComponent(tempJButton2)
                .addGap(18, 18, 18)
                .addComponent(tempJButton3)
                .addGap(16, 16, 16)
                .addComponent(jToggleButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempJButton1ActionPerformed
        // TODO add your handling code here:
        
       
        FTE theFTE;
        PTE thePTE;
        
        theFTE = new FTE(111111, "Elmer", "Fudd", 0, 3, 0.2, 80000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");
                
        thePTE = new PTE(222222, "Daffy", "Duck", 0, 2, 0.22, 10.0, 20.0, 30.0);
        theHT.addEmployee(thePTE);
        System.out.println("Added the PTE to the hash table!");
                
        theFTE = new FTE(333333, "Lola", "Bunny", 1, 5, 0.17, 90000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");

    }//GEN-LAST:event_tempJButton1ActionPerformed

    private void tempJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempJButton2ActionPerformed
        // TODO add your handling code here:
        PrintWriter out = null;
        try {
            out = new PrintWriter(new BufferedWriter(new FileWriter("database.txt")));
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
//        BACKUPDisplayEmployeeInfoJFrame theSeparateJFrame = new BACKUPDisplayEmployeeInfoJFrame();
//        theSeparateJFrame.setVisible(true);
//        //MyHashTable refVal = getTheHT();
//        //MyHashTable refVal = theHT;
//        theSeparateJFrame.setMainHT(theHT);  // Have theSeparateJFrame mainHT point to the real HT.

    }//GEN-LAST:event_tempJButton2ActionPerformed

    private void pressed_tempJButton3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_tempJButton3
        // TODO add your handling code here:
        DisplayEmployeeInfoJFrame newDEIJFrame = new DisplayEmployeeInfoJFrame();
        newDEIJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        newDEIJFrame.setMainHT(refVal);
    }//GEN-LAST:event_pressed_tempJButton3

    private void removeEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmpButtonActionPerformed
        // TODO add your handling code here:
        RemoveNewEmployeeJFrame newRNEJFrame = new RemoveNewEmployeeJFrame();
        newRNEJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        newRNEJFrame.setMainHT(refVal);
    }//GEN-LAST:event_removeEmpButtonActionPerformed

    private void getEmpInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmpInfoButtonActionPerformed
        // TODO add your handling code here:
        LookupEmployeeInfoJFrame newLEIJFrame = new LookupEmployeeInfoJFrame();
        newLEIJFrame.setVisible(true);
        newLEIJFrame.setMainHT(theHT);
    }//GEN-LAST:event_getEmpInfoButtonActionPerformed

    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        // TODO add your handling code here:
        AddNewEmployeeJFrame newANEJFrame = new AddNewEmployeeJFrame();
        newANEJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        newANEJFrame.setMainHT(refVal);
    }//GEN-LAST:event_addEmpButtonActionPerformed

    private void setEmpInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEmpInfoButtonActionPerformed
        // TODO add your handling code here:
        ChangeEmployeeInfoJFrame newCEIJFrame = new ChangeEmployeeInfoJFrame();
        newCEIJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        newCEIJFrame.setMainHT(refVal);
    }//GEN-LAST:event_setEmpInfoButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Writing to database file
        PrintWriter out = null;
        try {
            out = new PrintWriter(new BufferedWriter(new FileWriter("database.txt")));
            out.println("YES");
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(light){
            try {
                jToggleButton1.setText("Dark");
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                jToggleButton1.setText("Light");
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        light = !light;
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton getEmpInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton removeEmpButton;
    private javax.swing.JButton setEmpInfoButton;
    private javax.swing.JButton tempJButton1;
    private javax.swing.JButton tempJButton2;
    private javax.swing.JButton tempJButton3;
    // End of variables declaration//GEN-END:variables
}
